---
language: python
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libpulse-dev swig -y
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install textract
script:
  - ls -lR
  - python generate_resume_template.py
  - python check_wordfile.py
before_deploy:
  - git config --local user.name "t-v"
  - git config --local user.email "timothy.vandenbrande@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  name: Curiculum Vitae
  body: My from YAML generated resume.
  provider: releases
  api_key: $GH_TOKEN
    #secure: mobuyF7GOBkbVygm6CuKW/votv5vsz+xIJgMR/drm8gND/ZIpNGGv3xMYAoomWqEU6mq1oJ28bsEjiCR8BlA3W/Otz8GRM5e5eTTVbByiRUK1ER5SDXfQw6NozLn76lA0KQ1JMcapK3sKqUvJzuNT4JltaVyfsl0JjOmGWy9A8dRCzpFcwFv8pZN5OoEQId1L6RuvDLdGvXGTYH7kRrWZhUF6dmeQgW9cq/+tN0y9x+sgPw+DnYMvig3GqLEPSOhj84xJTR06ht41OL+2/SFdw8y7AI7Kyq4GgrnbIjwb0iIZL8C4cgk2M7mZQXNmhzgvNU4Pqee0bcTQPdzOlMSuhKo13FoZ3zS2jTzFjUJW8vNLKGizPE/+sF7WRnM7nVgANTavyZ1nBNIj+yihGmBl8AluUDszH+xmU/8HSVLx4h4iLgxjG76Z95Lj788sUZqo3IFD2KlaETou4Kev/eYY370NzPnUJOWTJGadMbjoL+DEpB5Cs36y0Sc5d0nBK959m3NbcnUMpBGlMbckZH7RB3eEC7QOhCvnmuUIauZJM32pKp1G9aQz9MmYoGTRHlIeSCpF1FvS+B4DfF1NWu5G+EUNE1zxF6uTDtzssU9+bCXlgK6LEP6KT9x3rz7iB5gyxxBmR0srmxkhF1qU5Tt/zMkBQU9zzoqoEdSIDJI8lQ=
  file:
    - output/resume.docx
    - output/resume.md
  skip_cleanup: true
  overwrite: true
