---
language: python
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libpulse-dev swig -y
python:
  - '3.8'
install:
  - pip install -r requirements.txt
  - pip install textract
script:
  - ls -lR
  - python generate_resume_template.py
  - python check_wordfile.py
before_deploy:
  - git config --local user.name "t-v"
  - git config --local user.email "timothy.vandenbrande@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  name: Curriculum Vitae
  body: My from YAML generated resume.
  provider: releases
  api_key: $GH_TOKEN
  file:
    - output/resume.docx
    - output/resume.md
  overwrite: true
  skip_cleanup: true
