#!/usr/bin/env node
/*
 * Applies the personal branding on top of the stock yamlresume templates.
 *
 * yamlresume's templates are not forkable: `layouts[].template` only accepts
 * the built-in template ids. Everything that can be expressed through the
 * schema (font family, font size, spacing, margins, section order and section
 * names) lives in the resume YAML itself. The two things the schema does not
 * expose are the colours, so they are patched in here:
 *
 *   - HTML: the "calm" template is built on CSS custom properties, so the
 *     palette is injected as a <style> block together with theme/resume-theme.css.
 *   - LaTeX: moderncv hardcodes \moderncvcolor{black}. Redefining color1/color2
 *     is not enough on its own, because moderncvstyle<style>.sty copies them
 *     into every derived colour with \colorlet, which resolves immediately. So
 *     \moderncvstyle is also moved below the new definitions, which makes the
 *     style derive sectioncolor, lastnamecolor, bodyrulecolor and friends from
 *     the brand palette instead of from black.
 *
 * It also drops the "Generated by YAMLResume" footer from the HTML.
 *
 * Usage: node scripts/apply-theme.mjs <output-basename-without-extension>
 *   e.g. node scripts/apply-theme.mjs output/t-v-resume
 *
 * The script is idempotent: re-running it on an already themed file is a no-op.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const BRAND = {
  accent: '8D281E',
  muted: '7F7F7F',
  fontFamily: 'Quicksand',
  fontWeights: '400;500;600;700',
  fallbackFonts:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
}

const MARKER = 'yamlresume-brand-theme'
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

function buildStyleBlock() {
  const css = readFileSync(resolve(repoRoot, 'theme/resume-theme.css'), 'utf8')
  const fontUrl =
    `https://fonts.googleapis.com/css2?family=${BRAND.fontFamily}` +
    `:wght@${BRAND.fontWeights}&display=swap`

  return [
    `<style id="${MARKER}">`,
    `@import url('${fontUrl}');`,
    ':root {',
    `  --brand-accent: #${BRAND.accent};`,
    `  --brand-muted: #${BRAND.muted};`,
    `  --brand-font: '${BRAND.fontFamily}', ${BRAND.fallbackFonts};`,
    '}',
    css.trim(),
    '</style>',
  ].join('\n')
}

function themeHtml(file, buildDate) {
  let html = readFileSync(file, 'utf8')

  if (html.includes(MARKER)) {
    console.log(`  = ${file} already themed, skipping`)
    return
  }
  if (!html.includes('</head>')) {
    throw new Error(`${file}: no </head> found, cannot inject the theme`)
  }

  html = html.replace('</head>', `${buildStyleBlock()}\n</head>`)

  // Drop the "Generated by YAMLResume" credit the template appends.
  html = html.replace(/\s*<footer class="resume-footer">[\s\S]*?<\/footer>/, '')

  const footer = `<footer class="resume-updated">Last updated on ${buildDate}</footer>`
  html = html.includes('</body>')
    ? html.replace('</body>', `${footer}\n</body>`)
    : html + footer

  writeFileSync(file, html)
  console.log(`  + ${file} themed (accent #${BRAND.accent}, ${BRAND.fontFamily})`)
}

// Entries are plain \cventry calls with nothing holding them together, so LaTeX
// happily leaves an employer/position/date header stranded at the bottom of a
// page with its body starting on the next one. Reserve room for the header plus
// a couple of body lines before each entry, and forbid widows and orphans.
//
// The needspace package is not in the build image, so its macro is inlined.
function texPageBreaks(tex, file) {
  const preamble = String.raw`% ${MARKER}: keep entries from splitting across pages
\makeatletter
\providecommand{\needspace}[1]{%
  \begingroup
    \setlength{\dimen@}{#1}%
    \vskip\z@\@plus\dimen@
    \penalty -100\vskip\z@\@plus -\dimen@
    \vskip\dimen@
    \penalty 9999\vskip -\dimen@
    \vskip\z@skip
  \endgroup}
\makeatother
\widowpenalty=10000
\clubpenalty=10000
\displaywidowpenalty=10000
% Long keyword lists have few break points, so give TeX extra room to stretch a
% line rather than letting it run into the margin.
\emergencystretch=3em
`

  if (!tex.includes('\\begin{document}')) {
    throw new Error(`${file}: no \\begin{document} found`)
  }

  tex = tex.replace('\\begin{document}', `${preamble}\n\\begin{document}`)

  let entries = 0
  tex = tex.replace(/^\\cventry/gm, () => {
    entries += 1
    return '\\needspace{5\\baselineskip}%\n\\cventry'
  })

  console.log(`  + ${file} ${entries} entries pinned against page breaks`)
  return tex
}

// Bring the PDF's colour weighting in line with the HTML, where the employer,
// the dates and the keyword lists are grey and only the body copy is black.
// moderncv renders all of them in flat black, which reads as much heavier.
//
//   - icons: moderncv defaults every contact/social icon to its own `darkgrey`,
//     so they are repainted in the accent colour.
//   - employer and dates: \cventry has no colour hook, so it is redefined. This
//     mirrors moderncvbodyiii.sty, with \color added to the relevant cells.
//   - keywords: patched in the body text further down, see texKeywords().
function texColours(tex, file) {
  const block = String.raw`% ${MARKER}: match the HTML's colour weighting
\colorlet{default-socialicon-color}{color1}
\colorlet{mobilephone}{color1}
\colorlet{fixedphone}{color1}
\colorlet{email}{color1}
\colorlet{homepage}{color1}
\colorlet{github}{color1}
\colorlet{linkedin}{color1}
\renewcommand*{\cventry}[7][.25em]{%
  \begin{tabular*}{\maincolumnwidth}{l@{\extracolsep{\fill}}r}%
    \ifboolexpr{%
      test {\ifstrempty{#4}}
      and
      test {\ifstrempty{#5}}}%
      {}%
      {{\bfseries\color{color2}#4} & {\bfseries\color{color2}#5}\\}%
    {\itshape #3\ifstrempty{#6}{}{, #6}} & {\itshape\color{color2}#2}\\%
  \end{tabular*}%
  \ifx&#7&%
  \else{\\%
    \begin{minipage}{\maincolumnwidth}%
      \small#7%
    \end{minipage}}\fi%
  \par\addvspace{#1}}
`

  tex = tex.replace('\\begin{document}', `${block}\n\\begin{document}`)

  // The \colorlet block above covers moderncv's own contact symbols, which carry
  // named colours. The profile icons are different: yamlresume writes them into
  // \extrainfo as bare \faGithub / \faLinkedin, so they just inherit the grey
  // address colour. Colour them explicitly.
  let icons = 0
  tex = tex.replace(/\{\\small \\fa([A-Za-z]+)\}/g, (_, name) => {
    icons += 1
    return `{\\small\\color{color1}\\fa${name}}`
  })

  console.log(`  + ${file} icons (${icons} inline) and entry headers recoloured`)
  return tex
}

// Keyword lists are the last thing in a \cventry body and in a skill \cvline, so
// an unbraced \color applies to exactly the rest of that group.
function texKeywords(tex, file) {
  let count = 0
  const patched = tex.replace(/\\textbf\{Keywords\}:/g, () => {
    count += 1
    return '\\color{color2}\\textbf{Keywords}:'
  })

  console.log(`  + ${file} ${count} keyword lists greyed`)
  return patched
}

// The moderncv/jake templates right-align the keyword list with \hfill, which
// leaves ragged gaps of wildly different widths and wraps long lists back to the
// left margin. The HTML template puts the keywords on their own line under the
// skill, so mirror that instead.
function texSkills(tex, file) {
  let skills = 0
  const patched = tex.replace(/ \\hfill \\textbf\{Keywords\}:/g, () => {
    skills += 1
    return '\\newline\\textbf{Keywords}:'
  })

  if (skills > 0) {
    console.log(`  + ${file} ${skills} skill rows reflowed onto two lines`)
  }
  return patched
}

function themeTex(file) {
  let tex = readFileSync(file, 'utf8')

  if (tex.includes(MARKER)) {
    console.log(`  = ${file} already themed, skipping`)
    return
  }

  const colorLine = /\\moderncvcolor\{[a-z]+\}/
  const styleLine = /^\\moderncvstyle\{[a-z]+\}\n/m

  if (!colorLine.test(tex)) {
    throw new Error(`${file}: no \\moderncvcolor{...} found, cannot recolour`)
  }

  const style = tex.match(styleLine)
  if (!style) {
    throw new Error(`${file}: no \\moderncvstyle{...} found, cannot recolour`)
  }

  // Lift \moderncvstyle out and re-emit it after the palette. The style file
  // derives every colour it uses with \colorlet, which copies the value there
  // and then, so it has to be loaded once color1/color2 already hold the brand
  // colours. Leaving it above would keep the whole document black.
  tex = tex.replace(styleLine, '')
  tex = tex.replace(
    colorLine,
    (match) =>
      `${match}\n% ${MARKER}\n` +
      `\\definecolor{color1}{HTML}{${BRAND.accent}}\n` +
      `\\definecolor{color2}{HTML}{${BRAND.muted}}\n` +
      style[0].trimEnd(),
  )

  // yamlresume emits this \href override whether or not typography.links.underline
  // is set, so every link in the document comes out underlined. Drop the block;
  // `underline: false` in the resume already stops the per-link \underline{}.
  const autoUnderline =
    /% Auto-underline all links\n(?:%[^\n]*\n)*\\AtBeginDocument\{%\n(?:[^\n]*\n)*?\}\n/

  if (autoUnderline.test(tex)) {
    tex = tex.replace(autoUnderline, '')
    console.log(`  + ${file} link underlining removed`)
  } else {
    console.log(`  ! ${file} no auto-underline block found (upstream may have fixed it)`)
  }

  tex = texPageBreaks(tex, file)
  tex = texSkills(tex, file)
  tex = texColours(tex, file)
  tex = texKeywords(tex, file)

  writeFileSync(file, tex)
  console.log(`  + ${file} recoloured (color1 #${BRAND.accent}, color2 #${BRAND.muted})`)
}

const basename = process.argv[2]
if (!basename) {
  console.error('usage: node scripts/apply-theme.mjs <output-basename-without-extension>')
  process.exit(1)
}

const buildDate = process.env.BUILD_DATE || new Date().toISOString().slice(0, 10)

console.log(`Applying brand theme to ${basename}.*`)

const html = `${basename}.html`
const tex = `${basename}.tex`

if (existsSync(html)) themeHtml(html, buildDate)
else console.log(`  - ${html} not found, skipping`)

if (existsSync(tex)) themeTex(tex)
else console.log(`  - ${tex} not found, skipping`)
