name: Release Resume

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget -y
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
          sudo apt install ./wkhtmltox_0.12.6-1.focal_amd64.deb -y
          python -m pip install --upgrade pip
          pip install build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build resume
        run: python ./generate_resume.py

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'

      - name: Get Time
        id: timeformatted
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD HH:mm:ss'
      
      - name: debug to check if files are still there
        run: ls -l output/
  
      - name: release it
        run: |
          set -x
          assets=()
          ls -l
          for asset in ./output/*; do
            echo $asset
            assets+=("-a" "$asset")
          done
          time=$TIME
          timeformat=$TIMEFORMAT
          hub release create "${assets[@]}" -m "Curiculum Vitae" -m "My from YAML generated resume." -m "Resume: $TIMEFORMAT" "$TIME"
        env:
          TIMEFORMAT: ${{ steps.timeformatted.outputs.time }}
          TIME: ${{ steps.time.outputs.time }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
